### PR TITLE
Add implementation of Huffman decompression

### PR DESCRIPTION
**Pull request by philippeitis**
This implementation is largely based on https://github.com/kovidgoyal/calibre/blob/master/src/calibre/ebooks/mobi/huffcdic.py

### CODE REVIEW

**Comment by vv9k** [comment]
@philippeitis, I'm working on merging the decompression algorithm to mobi but I have a few questions about the provided algorithm. What exactly are the `sections` that are supposted to go as a second argument to `decompress`? I managed to load a huff dictionary by passing the correct huff and cdic records but then got stuck at reader reaching end of file when I tried to pass the readable record range slices as sections.

**Comment by philippeitis** [comment]
Hi - I am a little busy, but as an initial starting point, https://github.com/kovidgoyal/calibre/blob/ba2bd3f01b89961546a09d3d04afa46d7822997b/src/calibre/ebooks/mobi/reader/mobi6.py should be helpful (CTRL+F HuffReader, CTRL+F unpack to see where the sections come from) - https://github.com/kovidgoyal/calibre/blob/master/src/calibre/ebooks/mobi/huffcdic.py

**Comment by philippeitis** [comment]
```
    def text_section(self, index):
        data = self.sections[index][0]
        trail_size = self.sizeof_trailing_entries(data)
        return data[:len(data)-trail_size]

    def extract_text(self, offset=1):
        self.log.debug('Extracting text...')
        text_sections = [self.text_section(i) for i in range(offset,
            min(self.book_header.records + offset, len(self.sections)))]
        processed_records = list(range(offset-1, self.book_header.records +
            offset))
...
        self.mobi_html = b''.join(map(unpack, text_sections))
```

**Comment by philippeitis** [comment]
```python
        self.sections = []
        self.section_headers = []
        for i in range(self.num_sections):
            offset, a1, a2, a3, a4 = struct.unpack('>LBBBB', raw[78 + i * 8:78 + i * 8 + 8])
            flags, val = a1, a2 << 16 | a3 << 8 | a4
            self.section_headers.append((offset, flags, val))

        def section(section_number):
            if section_number == self.num_sections - 1:
                end_off = len(raw)
            else:
                end_off = self.section_headers[section_number + 1][0]
            off = self.section_headers[section_number][0]
            return raw[off:end_off]

        for i in range(self.num_sections):
            self.sections.append((section(i), self.section_headers[i]))
```

**Comment by philippeitis** [comment]
@vv9k So, judging by this, I believe that we need to take the sections from `self.book_header.huff_offset..                  self.book_header.huff_offset + self.book_header.huff_number` as the huff tables, and the remaining sections in range `self.text_section(i) for i in range(offset, min(self.book_header.records + offset, len(self.sections)))`

**Comment by philippeitis** [comment]
Looking at `lib.rs`, `huff_data` looks correct to me.

**Comment by vv9k** [comment]
Thanks for the response :) When using only the `readable_record_range`, it currently fails with `InvalidDictionaryIndex` when trying to fetch a value from the huffman dictionary. The index is over the bounds of the dictionary, here are the values printed before indexing:
```
max_code: 75104255, code: 0, code_len: 17, index: 2291, dict_len: 2048
```

https://github.com/vv9k/mobi-rs/blob/277dc9d825d8dbfaea79e5a76eb4e3c7bc7224b6/src/huff.rs#L188-L194

Will have to look some more into it, just started wrapping my head around it.

**Pull request merged**
